workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - when: never

image: mcr.microsoft.com/playwright/java

stages:
  - test
  - report
  - verify

variables:
  accepted_rate:
    value: "100"
    description: "Accepted pass rate"

  testExecKey:
    description: "XRAY Test Execution Ticket ID"

  environment:
    value: "dev"
    description: "Target system"

  testScope:
    value: "login"
    description: "Define test scope"
    
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  TESTNG_SUITE: "src/test/resources/testng"


.platform_job:
  tags:
    - platform

.download_allure_history: &download_allure_history
  - mkdir backup && cd backup || true
  - curl -v --location --output report.zip --request GET "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/develop/download?job=pages&job_token=$CI_JOB_TOKEN" || true
  - (unzip report.zip) || true
  - cd ../
  - (cp -r backup/public/history/ target/allure-results/history) || true

.test_definition: &test_definition
  - echo "[Auto-Message] Start UI Test Cases execution"
  - >
      if [ "$testScope" == "login" ]; then
        echo "[Auto-Message] Running login test suite"
        mvn clean test -DsuiteXmlFile=src/test/resources/testng_suite_1.xml -Dheadless=true -Denvironment=$environment
      elif [ "$testScope" == "UserProfile" ]; then
        echo "[Auto-Message] Running UserProfile test suite"
        mvn clean test -DsuiteXmlFile=src/test/resources/testng_suite_2.xml -Dheadless=true -Denvironment=$environment
      elif [ "$testScope" == "CasesTable" ]; then
        echo "[Auto-Message] Running CasesTable test suite"
        mvn clean test -DsuiteXmlFile=src/test/resources/testng_suite_3.xml -Dheadless=true -Denvironment=$environment
      elif [ "$testScope" == "Kpi" ]; then
        echo "[Auto-Message] Running Kpi test suite"
        mvn clean test -DsuiteXmlFile=src/test/resources/testng_suite_4.xml -Dheadless=true -Denvironment=$environment
      elif [ "$testScope" == "platform" ]; then
        echo "[Auto-Message] Running platfrm test suite for node $CI_NODE_INDEX"
        mvn clean test -DsuiteXmlFile=src/test/resources/testng_suite_$CI_NODE_INDEX.xml -Dheadless=true -Denvironment=$environment
      else
        echo "[Auto-Message] Invalid value for test scope = $testScope"
        exit 1
      fi
  - echo "[Auto-Message] UI Test Cases execution is done"


.collect_reports: &collect_reports
  - mkdir public
  - cp target/surefire-reports/testng-results.xml public/testng-results_suite_$CI_NODE_INDEX.xml
  # - cp -r target/allure-results/ public

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository
#TODO add cache for allure history
#TODO optimize Maven dependencies to reduce build time

tests:
  stage: test
  extends: .platform_job
  script:
    - *test_definition
  after_script:
    - *collect_reports
  artifacts:
    when: always
    paths:
      - public
      - target/allure-results/
    expire_in: 1 week
    reports:
      junit:
        - $CI_PROJECT_DIR/target/surefire-reports/junitreports/TEST-*.xml
  except:
    variables:
      - $testScope == "platform"

parallel-tests:
  stage: test
  extends: .platform_job
  parallel: 4
  script:
    - *test_definition
  after_script:
    - *collect_reports
  artifacts:
    when: always
    paths:
      - public
      - target/allure-results/
    expire_in: 1 week
    reports:
      junit:
        - $CI_PROJECT_DIR/target/surefire-reports/junitreports/TEST-*.xml
  only:
    variables:
      - $testScope == "platform"
      
#TODO optimize Maven dependencies to reduce build time
merge_test_results:
  stage: report
  extends: .platform_job
  # needs: [parallel-tests]
  before_script:
    - apt-get update -y && apt-get install -y xmlstarlet
    - *download_allure_history
  script:
    - chmod +x src/test/resources/merge_testng_results.sh
    - cd public/
    - $CI_PROJECT_DIR/src/test/resources/merge_testng_results.sh
    - cd ..
    - mvn io.qameta.allure:allure-maven:report
    - mv target/site/allure-maven-plugin/* public
  artifacts:
    expire_in: 1 week
    paths:
      - public
      - target
    when: always
    reports:
      dotenv: public/results.env

Xray_report:
  stage: report
  needs: [merge_test_results]
  extends: .platform_job
  script:
    - |
      echo "[Auto-Message] Upload test result to Xray..."
      export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$client_id\",\"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
      echo $token
      curl -v -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer $token" --data @"$CI_PROJECT_DIR/public/testng-results.xml" "https://xray.cloud.getxray.app/api/v2/import/execution/testng?projectKey=PLATFORM&testExecKey=$testExecKey"
      echo "[Auto-Message] Upload test resul is done"
  rules:
    - if: '$testExecKey && $testExecKey != ""'
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - public

pages:
  stage: report
  extends: .platform_job
  needs: [merge_test_results]
  script:
    - echo "publish allure report to gitlab pages"
  artifacts:
    when: always
    paths:
      - public
    expire_in: 30 days

verify:
  stage: verify
  needs: [merge_test_results]
  extends: .platform_job
  script:
    - total=$((TOTAL_PASSED+TOTAL_FAILED))
    - pass_rate=$((TOTAL_PASSED*100/total))
    - echo "[Auto-Message] accepted rate is $accepted_rate , Pass rate is $pass_rate , Total TC is $total , Pass TC is $pass"
    - if [ $pass_rate -lt $accepted_rate ]; then echo "[Auto-Message] Failed UI Tests run below accepted pass rate"; exit 1; else echo "[Auto-Message] Success UI Tests run within accepted pass rate"; fi
